import React from 'react';

import './index.css';

import { StyledEngineProvider, createTheme, ThemeProvider } from '@mui/material/styles';

import { Provider } from 'react-redux';
import store from './redux/store';

import Routes from './components/routes';

const muiTheme = createTheme({
  palette: {
    type: 'light',
    primary: {
      main: '#3c7daa',
    },
    secondary: {
      main: '#95251e',
    },
  },
});

for (let i = 0; i < document.styleSheets.length; i++) {
  // this code is written for removing transparent background style from buttons
  // which is causing no background color. This style rule is generated by tailwindcss
  const sheet = document.styleSheets[i];
  if (sheet instanceof CSSStyleSheet) {
    try {
      const rules = sheet.cssRules || sheet.rules;
      for (let j = 0; j < rules.length; j++) {
        const rule = rules[j];
        if (
          rule.selectorText === 'button, [type="button"], [type="reset"], [type="submit"]' &&
          rule.style.backgroundColor === 'transparent'
        ) {
          rule.style.backgroundColor = '';
        }
      }
    } catch (e) {
      console.log(e.message);
    }
  }
}

function App() {
  return (
    <Provider store={store}>
      <StyledEngineProvider injectFirst>
        <ThemeProvider theme={muiTheme}>
          <Routes />
        </ThemeProvider>
      </StyledEngineProvider>
    </Provider>
  );
}

export default App;
